export default {
    mutations: {
        FETCH_GRAND_PRIX_START: 'FETCH_GRAND_PRIX_START',
        FETCH_GRAND_PRIX_END: 'FETCH_GRAND_PRIX_END',
        FETCH_NEXT_GP_START: 'FETCH_NEXT_GP_START',
        FETCH_NEXT_GP_END: 'FETCH_NEXT_GP_END',
        FETCH_GP_LIST_START: 'FETCH_GP_LIST_START',
        FETCH_GP_LIST_END: 'FETCH_GP_LIST_END',
        FETCH_TIPPS_LIST_END: 'FETCH_TIPPS_LIST_END'
    },
    getters: {
    },
    actions: {
        FETCH_GRAND_PRIX: 'FETCH_GRAND_PRIX',
        FETCH_NEXT_GP: 'FETCH_NEXT_GP',
        FETCH_GP_LIST: 'FETCH_GP_LIST',
        FETCH_TIPPS_LIST: 'FETCH_TIPPS_LIST'
    },
};