export const AUTH_REQUEST_LOADING = 'AUTH_REQUEST_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT_MUTATION = 'AUTH_LOGOUT_MUTATION';

export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const USER_SET_CURRENT_COMMUNITY = 'USER_SET_CURRENT_COMMUNITY';

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const USER_CHANGE_PWD_SUCCESS = 'USER_CHANGE_PWD_SUCCESS';
export const REMOVE_REGISTERED_MAIL_STATE = 'REMOVE_REGISTERED_MAIL_STATE';

export const FETCH_NEXT_GP_START = 'FETCH_NEXT_GP_START';
export const FETCH_NEXT_GP_END = 'FETCH_NEXT_GP_END';
export const FETCH_GP_LIST_START = 'FETCH_GP_LIST_START';
export const FETCH_GP_LIST_END = 'FETCH_GP_LIST_END';
export const FETCH_GRAND_PRIX_START = 'FETCH_NEXT_GRAND_PRIX_START';
export const FETCH_GRAND_PRIX_END = 'FETCH_NEXT_GRAND_PRIX_END';
export const FETCH_TIPPS_LIST_END = 'FETCH_TIPPS_LIST_END';
export const FETCH_DRIVERS_LIST_START = 'FETCH_DRIVERS_LIST_START';
export const FETCH_DRIVERS_LIST_END = 'FETCH_DRIVERS_LIST_END';
