export const FETCH_NEXT_GP_START = 'FETCH_NEXT_GP_START';
export const FETCH_NEXT_GP_END = 'FETCH_NEXT_GP_END';
export const FETCH_GP_LIST_START = 'FETCH_GP_LIST_START';
export const FETCH_GP_LIST_END = 'FETCH_GP_LIST_START';
export const FETCH_GRAND_PRIX_START = 'FETCH_NEXT_GRAND_PRIX_START';
export const FETCH_GRAND_PRIX_END = 'FETCH_NEXT_GRAND_PRIX_END';
