name: Deploy to Beta

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build
    uses: Cadiducho/PrognoSports-Frontend/.github/workflows/vite.yml@develop
    with:
      node_version: '20.x'
      build_command: 'buildBeta'
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: frontend
          path: ./dist
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SECRET_FRONTEND_HOST }}
          username: ${{ secrets.SECRET_FRONTEND_USER }}
          key: ${{ secrets.SECRET_FRONTEND_RSA }}
          port: ${{ secrets.SECRET_FRONTEND_PORT }}
          source: "dist/"
          target: ${{ secrets.SECRET_FRONTEND_BETA_PATH }}
          strip_components: 1