name: Deploy to Beta

on:
    push:
        branches: [ develop ]
        
jobs:
    deploy:
        name: Deploy    
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '16.x'
        - name: Install dependencies
          run: yarn install
        - name: Vue Build
          run: yarn run buildBeta
        - name: Upload to server
          uses: appleboy/scp-action@v0.1.3
          with:
            host: ${{ secrets.SECRET_FRONTEND_HOST }}
            username: ${{ secrets.SECRET_FRONTEND_USER }}
            key: ${{ secrets.SECRET_FRONTEND_RSA }}
            port: ${{ secrets.SECRET_FRONTEND_PORT }}
            source: "dist/"
            target: ${{ secrets.SECRET_FRONTEND_BETA_PATH }}
            strip_components: 1