name: Test PR

on:
  pull_request:
    branches: [ develop, master ]

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/vite.yml
    with:
      build_command: 'buildBeta'
      lint: true
