name: Vite CLI

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node version to build."
        type: string
        required: false
        default: '18.x'
      build_command:
        description: "Build command."
        type: string
        required: false
        default: 'build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - uses : actions/checkout@v3
      - uses : actions/setup-node@v3
        with :
          node-version : ${{ inputs.node_version }}
          cache: 'npm'
      - name : Install dependencies
        run : yarn install
      - name : 🏭 Vue Build
        run : yarn run ${{ inputs.build_command }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 'frontend'
          path: ./dist
          retention-days: 1