name: Vite CLI

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node version to build."
        type: string
        required: false
        default: '22.x'
      build_command:
        description: "Build command."
        type: string
        required: false
        default: 'build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - uses : actions/checkout@v4
      - uses : pnpm/action-setup@v4
        with :
          version : 8
      - uses : actions/setup-node@v4
        with :
          node-version : ${{ inputs.node_version }}
          cache: 'pnpm'
      - name : Install dependencies
        run : pnpm install
      - name : 🏭 Vue Build
        run : pnpm run ${{ inputs.build_command }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'frontend'
          path: ./dist
          retention-days: 1