export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const USER_FORGOT_PWD = 'USER_FORGOT_PWD';
export const USER_CHANGE_PWD = 'USER_CHANGE_PWD';
export const USER_CHANGE_PWD_SUCCESS = 'USER_CHANGE_PWD_SUCCESS';
export const REMOVE_REGISTERED_MAIL_STATE = 'REMOVE_REGISTERED_MAIL_STATE';